// ==================== AUDIO ====================
let actx=null;
function initAudio(){if(!actx)actx=new(window.AudioContext||window.webkitAudioContext)()}
function snd(type){
  if(!actx)return;const t=actx.currentTime;
  switch(type){
    case'punch':{const b=actx.createBuffer(1,actx.sampleRate*0.12,actx.sampleRate),d=b.getChannelData(0);for(let i=0;i<d.length;i++)d[i]=(Math.random()*2-1)*Math.pow(1-i/d.length,3.5);const n=actx.createBufferSource(),g=actx.createGain();n.buffer=b;n.connect(g);g.connect(actx.destination);g.gain.setValueAtTime(0.5,t);g.gain.exponentialRampToValueAtTime(0.001,t+0.12);n.start(t);const o=actx.createOscillator(),g2=actx.createGain();o.type='sawtooth';o.frequency.setValueAtTime(160,t);o.frequency.exponentialRampToValueAtTime(40,t+0.1);o.connect(g2);g2.connect(actx.destination);g2.gain.setValueAtTime(0.25,t);g2.gain.exponentialRampToValueAtTime(0.001,t+0.1);o.start(t);o.stop(t+0.12);break}
    case'kick':{const b=actx.createBuffer(1,actx.sampleRate*0.18,actx.sampleRate),d=b.getChannelData(0);for(let i=0;i<d.length;i++)d[i]=(Math.random()*2-1)*Math.pow(1-i/d.length,3);const n=actx.createBufferSource(),g=actx.createGain();n.buffer=b;n.connect(g);g.connect(actx.destination);g.gain.setValueAtTime(0.6,t);g.gain.exponentialRampToValueAtTime(0.001,t+0.18);n.start(t);const o=actx.createOscillator(),g2=actx.createGain();o.type='square';o.frequency.setValueAtTime(110,t);o.frequency.exponentialRampToValueAtTime(25,t+0.15);o.connect(g2);g2.connect(actx.destination);g2.gain.setValueAtTime(0.35,t);g2.gain.exponentialRampToValueAtTime(0.001,t+0.15);o.start(t);o.stop(t+0.18);break}
    case'heavy':{const b=actx.createBuffer(1,actx.sampleRate*0.25,actx.sampleRate),d=b.getChannelData(0);for(let i=0;i<d.length;i++)d[i]=(Math.random()*2-1)*Math.pow(1-i/d.length,2)*Math.sin(i*0.02);const n=actx.createBufferSource(),g=actx.createGain();n.buffer=b;n.connect(g);g.connect(actx.destination);g.gain.setValueAtTime(0.7,t);g.gain.exponentialRampToValueAtTime(0.001,t+0.25);n.start(t);const o=actx.createOscillator(),g2=actx.createGain();o.type='sawtooth';o.frequency.setValueAtTime(90,t);o.frequency.exponentialRampToValueAtTime(15,t+0.2);o.connect(g2);g2.connect(actx.destination);g2.gain.setValueAtTime(0.45,t);g2.gain.exponentialRampToValueAtTime(0.001,t+0.2);o.start(t);o.stop(t+0.25);break}
    case'block':{const o=actx.createOscillator(),g=actx.createGain();o.type='triangle';o.frequency.setValueAtTime(900,t);o.frequency.exponentialRampToValueAtTime(300,t+0.08);o.connect(g);g.connect(actx.destination);g.gain.setValueAtTime(0.15,t);g.gain.exponentialRampToValueAtTime(0.001,t+0.08);o.start(t);o.stop(t+0.1);break}
    case'ultimate':{const b=actx.createBuffer(1,actx.sampleRate*0.45,actx.sampleRate),d=b.getChannelData(0);for(let i=0;i<d.length;i++)d[i]=(Math.random()*2-1)*Math.pow(1-i/d.length,1.2)*Math.sin(i*0.04);const n=actx.createBufferSource(),g=actx.createGain();n.buffer=b;n.connect(g);g.connect(actx.destination);g.gain.setValueAtTime(0.8,t);g.gain.exponentialRampToValueAtTime(0.001,t+0.45);n.start(t);const o=actx.createOscillator(),g2=actx.createGain();o.type='sawtooth';o.frequency.setValueAtTime(220,t);o.frequency.exponentialRampToValueAtTime(25,t+0.35);o.connect(g2);g2.connect(actx.destination);g2.gain.setValueAtTime(0.5,t);g2.gain.exponentialRampToValueAtTime(0.001,t+0.35);o.start(t);o.stop(t+0.45);break}
    case'hit':{const o=actx.createOscillator(),g=actx.createGain();o.type='square';o.frequency.setValueAtTime(350,t);o.frequency.exponentialRampToValueAtTime(80,t+0.06);o.connect(g);g.connect(actx.destination);g.gain.setValueAtTime(0.12,t);g.gain.exponentialRampToValueAtTime(0.001,t+0.06);o.start(t);o.stop(t+0.07);break}
    case'death':{const o=actx.createOscillator(),g=actx.createGain();o.type='sawtooth';o.frequency.setValueAtTime(300,t);o.frequency.exponentialRampToValueAtTime(20,t+1);o.connect(g);g.connect(actx.destination);g.gain.setValueAtTime(0.4,t);g.gain.exponentialRampToValueAtTime(0.001,t+1);o.start(t);o.stop(t+1);break}
    case'victory':{[523,659,784,1047].forEach((f,i)=>{const o=actx.createOscillator(),g=actx.createGain();o.type='square';o.frequency.value=f;o.connect(g);g.connect(actx.destination);g.gain.setValueAtTime(0,t+i*0.15);g.gain.linearRampToValueAtTime(0.2,t+i*0.15+0.04);g.gain.exponentialRampToValueAtTime(0.001,t+i*0.15+0.35);o.start(t+i*0.15);o.stop(t+i*0.15+0.35)});break}
    case'select':{const o=actx.createOscillator(),g=actx.createGain();o.type='sine';o.frequency.setValueAtTime(700,t);o.frequency.setValueAtTime(900,t+0.04);o.connect(g);g.connect(actx.destination);g.gain.setValueAtTime(0.12,t);g.gain.exponentialRampToValueAtTime(0.001,t+0.1);o.start(t);o.stop(t+0.1);break}
    case'whoosh':{const b=actx.createBuffer(1,actx.sampleRate*0.2,actx.sampleRate),d=b.getChannelData(0);for(let i=0;i<d.length;i++)d[i]=(Math.random()*2-1)*Math.pow(1-i/d.length,6)*0.5;const n=actx.createBufferSource(),g=actx.createGain();n.buffer=b;n.connect(g);g.connect(actx.destination);g.gain.setValueAtTime(0.3,t);g.gain.exponentialRampToValueAtTime(0.001,t+0.2);n.start(t);break}
    case'slam':{const b=actx.createBuffer(1,actx.sampleRate*0.4,actx.sampleRate),d=b.getChannelData(0);for(let i=0;i<d.length;i++)d[i]=(Math.random()*2-1)*Math.pow(1-i/d.length,2)*0.8;const n=actx.createBufferSource(),g=actx.createGain();n.buffer=b;n.connect(g);g.connect(actx.destination);g.gain.setValueAtTime(0.7,t);g.gain.exponentialRampToValueAtTime(0.001,t+0.4);n.start(t);const o=actx.createOscillator(),g2=actx.createGain();o.type='sine';o.frequency.setValueAtTime(60,t);o.frequency.exponentialRampToValueAtTime(15,t+0.3);o.connect(g2);g2.connect(actx.destination);g2.gain.setValueAtTime(0.5,t);g2.gain.exponentialRampToValueAtTime(0.001,t+0.3);o.start(t);o.stop(t+0.4);break}
    case'dash':{const b=actx.createBuffer(1,actx.sampleRate*0.15,actx.sampleRate),d=b.getChannelData(0);for(let i=0;i<d.length;i++)d[i]=(Math.random()*2-1)*Math.pow(1-i/d.length,5)*0.3;const n=actx.createBufferSource(),g=actx.createGain();n.buffer=b;n.connect(g);g.connect(actx.destination);g.gain.setValueAtTime(0.25,t);g.gain.exponentialRampToValueAtTime(0.001,t+0.15);n.start(t);break}
    case'crit':{const b=actx.createBuffer(1,actx.sampleRate*0.3,actx.sampleRate),d=b.getChannelData(0);for(let i=0;i<d.length;i++)d[i]=(Math.random()*2-1)*Math.pow(1-i/d.length,2)*Math.sin(i*0.05);const n=actx.createBufferSource(),g=actx.createGain();n.buffer=b;n.connect(g);g.connect(actx.destination);g.gain.setValueAtTime(0.8,t);g.gain.exponentialRampToValueAtTime(0.001,t+0.3);n.start(t);const o=actx.createOscillator(),g2=actx.createGain();o.type='sawtooth';o.frequency.setValueAtTime(200,t);o.frequency.exponentialRampToValueAtTime(30,t+0.25);o.connect(g2);g2.connect(actx.destination);g2.gain.setValueAtTime(0.5,t);g2.gain.exponentialRampToValueAtTime(0.001,t+0.25);o.start(t);o.stop(t+0.3);break}
    case'parry':{const o=actx.createOscillator(),g=actx.createGain();o.type='sine';o.frequency.setValueAtTime(1200,t);o.frequency.exponentialRampToValueAtTime(400,t+0.12);o.connect(g);g.connect(actx.destination);g.gain.setValueAtTime(0.3,t);g.gain.exponentialRampToValueAtTime(0.001,t+0.12);o.start(t);o.stop(t+0.15);break}
  }
}
let bgmGain=null,bgmOscs=[],bgmOn=false,bgmBeat=null;
function startBGM(){
  if(!actx||bgmOn)return;bgmOn=true;bgmGain=actx.createGain();bgmGain.gain.value=0.04;bgmGain.connect(actx.destination);
  [55,82.4,110].forEach(f=>{const o=actx.createOscillator();o.type='sawtooth';o.frequency.value=f;const g=actx.createGain();g.gain.value=0.4;o.connect(g);g.connect(bgmGain);o.start();bgmOscs.push(o)});
  const lfo=actx.createOscillator();lfo.frequency.value=0.15;const lg=actx.createGain();lg.gain.value=8;lfo.connect(lg);bgmOscs.forEach(o=>lg.connect(o.frequency));lfo.start();bgmOscs.push(lfo);
  let beat=0;bgmBeat=setInterval(()=>{if(!actx)return;beat++;const bt=actx.currentTime;const k=actx.createOscillator(),kg=actx.createGain();k.type='sine';k.frequency.setValueAtTime(100,bt);k.frequency.exponentialRampToValueAtTime(30,bt+0.1);k.connect(kg);kg.connect(bgmGain);kg.gain.setValueAtTime(0.3,bt);kg.gain.exponentialRampToValueAtTime(0.001,bt+0.1);k.start(bt);k.stop(bt+0.1);if(beat%2===0){const hh=actx.createBuffer(1,actx.sampleRate*0.05,actx.sampleRate),hd=hh.getChannelData(0);for(let i=0;i<hd.length;i++)hd[i]=(Math.random()*2-1)*Math.pow(1-i/hd.length,8);const hn=actx.createBufferSource(),hg=actx.createGain();hn.buffer=hh;hn.connect(hg);hg.connect(bgmGain);hg.gain.setValueAtTime(0.15,bt);hg.gain.exponentialRampToValueAtTime(0.001,bt+0.05);hn.start(bt)}},400);
}
function stopBGM(){bgmOscs.forEach(o=>{try{o.stop()}catch(e){}});bgmOscs=[];if(bgmBeat)clearInterval(bgmBeat);bgmBeat=null;bgmOn=false}